export const CHAT = {
    ON_CHAT_INPUT_CHANGE: 'ON_CHAT_INPUT_CHANGE',
    ON_CHAT_INPUT_SUBMIT: 'ON_CHAT_INPUT_SUBMIT',
}

export const CONTACTS = {
    ON_CONTACTS_SEARCH_INPUT_CHANGE: 'ON_CONTACTS_SEARCH_INPUT_CHANGE',
}

export const USERS = {
    FETCH_USERS: 'FETCH_USERS',
    FETCH_USERS_SUCCES: 'FETCH_USERS_SUCCES',
    FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',
}

export const DIALOGS = {
    FETCH_DIALOGS: 'FETCH_DIALOGS',
    FETCH_DIALOGS_SUCCES: 'FETCH_DIALOGS_SUCCES',
    FETCH_DIALOGS_FAIL: 'FETCH_DIALOGS_FAIL',
    SET_WAITING_STATUS: 'SET_WAITING_STATUS'
}

export const MESSAGES = {
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    FETCH_MESSAGES_SUCCES: 'FETCH_MESSAGES_SUCCES',
    FETCH_MESSAGES_FAIL: 'FETCH_MESSAGES_FAIL',
}

export const AUTH = {
    ON_INPUT_CHANGE: 'ON_INPUT_CHANGE',
    ON_INPUT_SUBMIT: 'ON_INPUT_SUBMIT',
    FETCH_AUTH_DATA_SUCCESS: 'FETCH_AUTH_DATA_SUCCESS',
    FETCH_AUTH_DATA_FAIL: 'FETCH_AUTH_DATA_FAIL',
    SET_WAITING_STATUS: 'SET_WAITING_STATUS'
}